baseurl      = "/"
title        = "CzrSec"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

PygmentsCodeFences = true
PygmentsStyle = "one-dark"

enableEmoji     = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "CzrSec"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Cyber Security Researcher, Pen-tester, Consultant"
  keywords = "cyber, security, offsec"
  images = [""]

  enableThemeToggle = true

  customCSS = []
  customJS  = []


  [params.footer]
    trademark = true
    rss = false
    copyright = true
    author = true

    topText = []
    bottomText = []

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/czrsec"

  [[params.social]]
    name = "email"
    url  = "mailto:helo@czrsec.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/czrsec"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "CzrSec"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoMark = "#"
      logoText = "whois czrsec"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.params.portrait]
      path = "/images/czrsec.jpg"
      alt = "Apes Together Strong"
      maxWidth = "200px"

  # And you can even create generic menu
  [[menu.main]]
    #identifier = "blog"
    #name       = "Blog"
    #url        = "/posts"